const products=[
    {
        _id:'1',
        name:'Airpods ',
        image:'/images/airpods.jpg',
        description:
        'Thelocation property of the window object will tell you the URL of the current page',
        brand:'Apple',
        category:'Electronics',
        price:89.99,
        countItStock:8,
        rating:4.5,
        numReviews:4,
    },
        {_id:'2',
        name:'Alexa ',
        image:'/images/alexa.jpg',
        description:
        'The browser represents each window or tab using a window object.',
        brand:'Apple',
        category:'Electronics',
        price:15.99,
        countItStock:3,
        rating:4.5,
        numReviews:4,
    },
        {_id:'3',
        name:'Camera ',
        image:'/images/camera.jpg',
        description:
        'Congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna',
        brand:'Apple',
        category:'Electronics',
        price:45.99,
        countItStock:3,
        rating:4.5,
        numReviews:4,
    },
        {_id:'4',
        name:'Mouse ',
        image:'/images/mouse.jpg',
        description:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor ',
        brand:'Apple',
        category:'Electronics',
        price:67.99,
        countItStock:33,
        rating:5.5,
        numReviews:4,
    },
        {_id:'5',
        name:'Phone ',
        image:'/images/phone.jpg',
        description:
        'Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.',
        brand:'Apple',
        category:'Electronics',
        price:9.99,
        countItStock:3,
        rating:1.5,
        numReviews:4,
    },
        {_id:'6',
        name:'Playstation ',
        image:'/images/playstation.jpg',
        description:
        'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.',
        brand:'Apple',
        category:'Electronics',
        price:29.99,
        countItStock:3,
        rating:3.5,
        numReviews:4,
    }
]

export default products