export const ORDERBIN_CREATE_REQUEST='ORDERBIN_CREATE_REQUEST'
export const ORDERBIN_CREATE_SUCCESS='ORDERBIN_CREATE_SUCCESS'
export const ORDERBIN_CREATE_FAIL='ORDERBIN_CREATE_FAIL'
export const ORDERBIN_CREATE_RESET='ORDERBIN_CREATE_RESET'

export const ORDERBIN_DETAILS_REQUEST='ORDERBIN_DETAILS_REQUEST'
export const ORDERBIN_DETAILS_SUCCESS='ORDERBIN_DETAILS_SUCCESS'
export const ORDERBIN_DETAILS_FAIL='ORDERBIN_DETAILS_FAIL'

export const ORDERBIN_PAY_REQUEST='ORDERBIN_PAY_REQUEST'
export const ORDERBIN_PAY_SUCCESS='ORDERBIN_PAY_SUCCESS'
export const ORDERBIN_PAY_FAIL='ORDERBIN_PAY_FAIL'
export const ORDERBIN_PAY_RESET='ORDERBIN_PAY_RESET'

export const ORDERBIN_LIST_MY_REQUEST='ORDERBIN_LIST_MY_REQUEST'
export const ORDERBIN_LIST_MY_SUCCESS='ORDERBIN_LIST_MY_SUCCESS'
export const ORDERBIN_LIST_MY_FAIL='ORDERBIN_LIST_MY_FAIL'
export const ORDERBIN_LIST_MY_RESET='ORDERBIN_LIST_MY_RESET'

export const ORDERBIN_LIST_REQUEST='ORDERBIN_LIST_REQUEST'
export const ORDERBIN_LIST_SUCCESS='ORDERBIN_LIST_SUCCESS'
export const ORDERBIN_LIST_FAIL='ORDERBIN_LIST_FAIL'
export const ORDERBIN_LIST_RESET='ORDERBIN_LIST_RESET'

export const ORDERBIN_DELIVERED_REQUEST='ORDERBIN_DELIVERED_REQUEST'
export const ORDERBIN_DELIVERED_SUCCESS='ORDERBIN_DELIVERED_SUCCESS'
export const ORDERBIN_DELIVERED_FAIL='ORDERBIN_DELIVERED_FAIL'
export const ORDERBIN_DELIVERED_RESET='ORDERBIN_DELIVERED_RESET'
