export const PICKUP_CREATE_REQUEST='PICKUP_CREATE_REQUEST'
export const PICKUP_CREATE_SUCCESS='PICKUP_CREATE_SUCCESS'
export const PICKUP_CREATE_FAIL='PICKUP_CREATE_FAIL'
export const PICKUP_CREATE_RESET='PICKUP_CREATE_RESET'

export const PICKUP_DETAILS_REQUEST='PICKUP_DETAILS_REQUEST'
export const PICKUP_DETAILS_SUCCESS='PICKUP_DETAILS_SUCCESS'
export const PICKUP_DETAILS_FAIL='PICKUP_DETAILS_FAIL'

export const PICKUP_LIST_REQUEST='PICKUP_LIST_REQUEST'
export const PICKUP_LIST_SUCCESS='PICKUP_LIST_SUCCESS'
export const PICKUP_LIST_FAIL='PICKUP_LIST_FAIL'
export const PICKUP_LIST_RESET='PICKUP_LIST_RESET'

export const PICKUP_DELIVERED_REQUEST='PICKUP_DELIVERED_REQUEST'
export const PICKUP_DELIVERED_SUCCESS='PICKUP_DELIVERED_SUCCESS'
export const PICKUP_DELIVERED_FAIL='PICKUP_DELIVERED_FAIL'
export const PICKUP_DELIVERED_RESET='PICKUP_DELIVERED_RESET'



export const PICKUP_LIST_MY_REQUEST='PICKUP_LIST_MY_REQUEST'
export const PICKUP_LIST_MY_SUCCESS='PICKUP_LIST_MY_SUCCESS'
export const PICKUP_LIST_MY_FAIL='PICKUP_LIST_MY_FAIL'
export const PICKUP_LIST_MY_RESET='PICKUP_LIST_MY_RESET'





