export const REPORT_CREATE_REQUEST='REPORT_CREATE_REQUEST'
export const REPORT_CREATE_SUCCESS='REPORT_CREATE_SUCCESS'
export const REPORT_CREATE_FAIL='REPORT_CREATE_FAIL'
export const REPORT_CREATE_RESET='REPORT_CREATE_RESET'



export const REPORT_LIST_REQUEST='REPORT_LIST_REQUEST'
export const REPORT_LIST_SUCCESS='REPORT_LIST_SUCCESS'
export const REPORT_LIST_FAIL='REPORT_LIST_FAIL'
export const REPORT_LIST_RESET='REPORT_LIST_RESET'


export const REPORT_DETAILS_REQUEST='REPORT_DETAILS_REQUEST'
export const REPORT_DETAILS_SUCCESS='REPORT_DETAILS_SUCCESS'
export const REPORT_DETAILS_FAIL='REPORT_DETAILS_FAIL'

// export const REPORT_DELIVERED_REQUEST='REPORT_DELIVERED_REQUEST'
// export const REPORT_DELIVERED_SUCCESS='REPORT_DELIVERED_SUCCESS'
// export const REPORT_DELIVERED_FAIL='REPORT_DELIVERED_FAIL'
// export const REPORT_DELIVERED_RESET='REPORT_DELIVERED_RESET'

// export const REPORT_LIST_MY_REQUEST='REPORT_LIST_MY_REQUEST'
// export const REPORT_LIST_MY_SUCCESS='REPORT_LIST_MY_SUCCESS'
// export const REPORT_LIST_MY_FAIL='REPORT_LIST_MY_FAIL'
// export const REPORT_LIST_MY_RESET='REPORT_LIST_MY_RESET'